version: '3'

services:
  backend:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - REDIS_HOST=redis

  frontend:
    build:
      dockerfile: ./Frontend/Dockerfile
    ports:
      - "8501:8501"
    command: streamlit run Frontend/streamlitFront.py
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"